

services:

  frontend:
    image: ghcr.io/izabi-ms/task-manager-frontend:latest
    container_name: task-manager-frontend-prod
    ports:
      - "80:80"
    depends_on:
      - backend


  backend:
    image: ghcr.io/izabi-ms/task-manager-backend:latest
    container_name: task-manager-backend-prod
    ports:
      - "5000:5000"

    environment:
      DATABASE_URL: ${DATABASE_URL}

    depends_on:
     db:
      condition: service_healthy

    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "http://localhost:5000/api/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 3


  db:
    image: postgres:16-alpine
    container_name: task-manager-db-prod

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

      
volumes:
  postgres_data: